apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: com-ecommerce-production  
  labels:
    app: aggregator
    version: "1.0"
    envitroment: production    
spec:
  selector:
    app: aggregator
    version: "1.0"
    envitroment: production    
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  namespace: com-ecommerce-production    
  labels:
    app: aggregator
    version: "1.0"
    envitroment: production       
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aggregator
      version: "1.0"
      envitroment: production         
  template:
    metadata:
      labels:
        app: aggregator
        version: "1.0"
        envitroment: production   
    spec:
      containers:
      - name: aggregator-container
        image: kkaggarwal/aggregator-service:0.0.5
        ports:
        - containerPort: 8082
        env:
          - name: QUOTES_USER_URL
            valueFrom:
              configMapKeyRef:
                name: services-properties-config-maps
                key: QUOTES_USER_URL
          - name: QUOTES_ORDER_URL
            valueFrom:
              configMapKeyRef:
                name: services-properties-config-maps
                key: QUOTES_ORDER_URL
          - name: opentracing.jaeger.udp-sender.host
            valueFrom:
              configMapKeyRef:
                name: services-properties-config-maps
                key: JAEGER_UDP_SENDER_HOST