apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: com-ecommerce-production
  labels:
    app: mysql
    version: "1.0"
    environment: production
spec:
  selector:
    app: mysql
    version: "1.0"
    environment: production
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: com-ecommerce-production
  labels:
    app: mysql
    version: "1.0"
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: "1.0"
      environment: production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: "1.0"
        environment: production
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: initdb-config  
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim